version: '3.8'

services:
  backend-python:
    build:
      context: ./backend-python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend-python:/app  # Mapeo para desarrollo en caliente
    environment:
      - PYTHONUNBUFFERED=1 # Para que los logs de Python aparezcan inmediatamente 